Max-Mobility/permobil-client

apps/wear/pushtracker/app/App_Resources/Android/src/main/java/com/permobil/pushtracker/wearos/ActivityService.java
apps/wear/pushtracker/app/App_Resources/Android/src/main/java/com/permobil/pushtracker/wearos/BootReceiver.java
apps/wear/pushtracker/app/pages/main-page/main-view-model.ts
apps/wear/smartdrive/app/assets/i18n/en.json

Need to update our approach to collecting and processing sensor data so that we consume as little cpu time / battery as possible.

Fix Battery Life and CPU Utilization in PushTracker WearOS

---

apps/wear/smartdrive/app/pages/main-page/main-view-model.ts

don't create oldest day record on first run / save and use instead each day's start values for computation.

Simplify Distance Storage and Computation

---

apps/mobile/pushtracker/src/app/modules/forgot-password/forgot-password.component.html
apps/mobile/pushtracker/src/app/modules/forgot-password/forgot-password.component.ts
apps/mobile/pushtracker/src/app/modules/sign-up/sign-up.component.html
apps/mobile/pushtracker/src/app/modules/sign-up/sign-up.component.ts
apps/mobile/pushtracker/src/app/scss/sign-up/_sign-up-base.scss
apps/mobile/pushtracker/src/app/scss/sign-up/_sign-up-dark.scss
apps/mobile/pushtracker/src/app/scss/sign-up/_sign-up-default.scss

Improved styling to match the rest of the app.

Fix login / sign-up / forgot password styles on ios 13 dark mode.

---

apps/wear/smartdrive/app/App_Resources/Android/src/main/AndroidManifest.xml
apps/wear/smartdrive/app/App_Resources/Android/src/main/res/values/strings.xml
apps/wear/smartdrive/app/App_Resources/Android/src/main/res/values/styles.xml

Bug/555 & 556

---

apps/wear/smartdrive/app/App_Resources/Android/src/main/java/com/permobil/smartdrive/wearos/watchface/digital/DigitalWatchFaceService.java

- Gets the shared preferences instance from the SD.W app inside the watchface service.
- When the watch face is updated in the `onDraw()` method will attempt to read the `sd.battery` key value out of sharedPrefs and set the value on the SD battery circle in the watchface UI.

Feature:557

---

apps/wear/smartdrive/app/App_Resources/Android/src/main/java/com/permobil/smartdrive/wearos/watchface/digital/DigitalWatchFaceService.java

Just commented out the default complication provider for the top complication in the watchface

closes #573

---

apps/mobile/pushtracker/src/app/models/pushtracker.model.ts
apps/mobile/pushtracker/src/app/namespaces/smartdrive-data.ts
apps/mobile/pushtracker/src/app/services/file.service.ts
apps/mobile/pushtracker/src/app/services/firmware.service.ts
apps/mobile/pushtracker/src/app/services/translation.service.ts
apps/mobile/pushtracker/src/app/utils/tns-translate-loader.ts

Closes 562

---

apps/mobile/pushtracker/src/app/modules/shared/components/pushtracker-status-button/pushtracker-status-button.component.ts

* SD Battery should show `--` instead of `0 %`
* Show PT address and group info better in the case of multiple PTs connected.

PT / SD battery display update

---

apps/wear/smartdrive/app/pages/main-page/main-view-model.ts
apps/wear/smartdrive/app/pages/modals/updates/updates-view-model.ts

Removed sentry breadcrumb in SD.W for timeReceiverCallback

---

apps/wear/smartdrive/app/pages/modals/updates/updates-view-model.ts

Sorry, missed the SEARCH/REPLACE in a few places.

Added debounced close method to OTA page

---

@permobil/core/src/models/device.settings.model.ts
@permobil/nativescript/src/plugins/nativescript-wear-os-comms/src/android/wear-os-comms.ts
@permobil/nativescript/src/utils/i18n.util.ts
apps/mobile/smart-eval/src/services/bluetooth.service.ts
apps/wear/pushtracker/app/models/activity-detector.ts
apps/wear/pushtracker/app/namespaces/profile.ts
apps/wear/pushtracker/app/pages/main-page/main-view-model.ts
apps/wear/pushtracker/app/pages/modals/change-settings/change-settings-view-model.ts
apps/wear/smartdrive/app/pages/main-page/main-view-model.ts
apps/wear/smartdrive/app/pages/modals/updates/updates-view-model.ts
apps/wear/smartdrive/app/services/network.service.ts
apps/wear/smartdrive/app/services/sqlite.service.ts

* Changed `map` to `forEach` when return value is discarded
* Using `isNaN` instead of `(foo === NaN)`

Code quality improvements

---

apps/mobile/pushtracker/App_Resources/Android/app.gradle
apps/mobile/pushtracker/App_Resources/iOS/Info.plist
apps/wear/smartdrive/app/pages/main-page/main-view-model.ts

Chore: 648 - bump version codes

---

@permobil/angular/package.json
@permobil/nativescript/package.json
apps/mobile/pushtracker/package.json
apps/mobile/pushtracker/src/main.ts
apps/mobile/pushtracker/webpack.config.js
apps/wear/pushtracker/package.json
apps/wear/pushtracker/webpack.config.js
package.json

Chore/647 - NS update

---

@permobil/nativescript/src/plugins/nativescript-wear-os-comms/src/android/wear-os-comms.ts

Bug: remove await on non promise method

---

apps/mobile/pushtracker/src/app/services/location.service.ts
apps/wear/pushtracker/app/pages/main-page/main-view-model.ts
apps/wear/pushtracker/app/pages/modals/about/about.ts
apps/wear/pushtracker/app/pages/modals/change-settings/change-settings-view-model.ts
apps/wear/pushtracker/app/pages/modals/synchronizing/synchronizing.ts
apps/wear/smartdrive/app/pages/main-page/main-view-model.ts
apps/wear/smartdrive/app/pages/modals/about/about.ts
apps/wear/smartdrive/app/pages/modals/error_history/error_history.ts
apps/wear/smartdrive/app/pages/modals/scanning/scanning.ts
apps/wear/smartdrive/app/pages/modals/settings/settings-view-model.ts
apps/wear/smartdrive/app/pages/modals/updates/updates-view-model.ts
apps/wear/smartdrive/app/utils/free-form-speech.ts
forked-plugins/nativescript-bluetooth/android/TNS_BluetoothGattCallback.ts
forked-plugins/nativescript-bluetooth/android/TNS_BroadcastReceiver.ts
forked-plugins/nativescript-bluetooth/android/android_main.ts

- Removed assertions that weren't useful.
- Also formatted files removing unused imports (most of the line changes)

Chore: 679 - SonarCloud unnecessary assertions

---

apps/mobile/pushtracker/src/app/modules/profile-tab/profile-tab.component.ts
apps/mobile/pushtracker/src/app/modules/wireless-updates/wireless-updates.component.ts
apps/mobile/pushtracker/src/app/namespaces/smartdrive-data.ts
apps/mobile/pushtracker/src/app/services/activity.service.ts
apps/mobile/pushtracker/src/app/services/settings.service.ts
apps/mobile/pushtracker/src/app/services/translation.service.ts
apps/wear/pushtracker/app/pages/modals/about/about.ts
apps/wear/smartdrive/app/models/smartdrive.ts
apps/wear/smartdrive/app/pages/main-page/main-view-model.ts
apps/wear/smartdrive/app/pages/modals/about/about.ts
apps/wear/smartdrive/app/pages/modals/updates/updates-view-model.ts

Fixed some code smell warnings per SonarCloud analysis. No functionality should be impacted, just renamed variables in some instances or commented out 'useless' for now until someone can confirm the reason we don't use them in another PR.

Chore: 677 - SonarCloud code smells

---

apps/wear/pushtracker/app/pages/main-page/main-page.ts
apps/wear/pushtracker/app/pages/main-page/main-page.xml
apps/wear/pushtracker/app/pages/main-page/main-view-model.ts

to simplify user interface and make it more responsive.

Remove pager from pt wear

---

apps/wear/smartdrive/app/namespaces/smartdrive-data.ts
apps/wear/smartdrive/app/pages/modals/updates/updates-page.ts
apps/wear/smartdrive/app/pages/modals/updates/updates-page.xml
apps/wear/smartdrive/app/pages/modals/updates/updates-view-model.ts
apps/wear/smartdrive/package.json

Looks good, so making the PR for now, just need to pair a SD and run the tests tomorrow to ensure nothing was missed.
Closes #772

Chore/772 - removing download-progress dep

---

apps/wear/smartdrive/app/App_Resources/Android/src/main/AndroidManifest.xml

Adds the flag to the watchface service, also formatted doc inside android studio.

Closes #781 - direct boot aware for watchface

---

apps/wear/smartdrive/app/App_Resources/Android/app.gradle

bumps version code for a bug release

Closes #811

---

@permobil/nativescript/package.json
@permobil/nativescript/references.d.ts
@permobil/nativescript/src/utils/device.util.ts
apps/mobile/pushtracker/package.json
apps/mobile/pushtracker/references.d.ts
apps/mobile/pushtracker/src/app/modules/profile-tab/profile-tab.component.ts
apps/mobile/pushtracker/src/app/modules/tabs/tabs.component.ts
apps/wear/pushtracker/app/pages/modals/about/about.ts
apps/wear/smartdrive/app/App_Resources/Android/src/main/java/com/permobil/smartdrive/wearos/watchface/digital/DigitalWatchFaceService.java
apps/wear/smartdrive/app/pages/main-page/main-view-model.ts
apps/wear/smartdrive/app/pages/modals/about/about.ts
apps/wear/smartdrive/app/pages/modals/updates/updates-view-model.ts

Adds the watch serial number to the sentry logs.

Feature: Updating Sentry logging with serial number

---

@permobil/core/src/enums/data-keys.ts
@permobil/core/src/index.d.ts
@permobil/nativescript/package.json
@permobil/nativescript/src/utils/android.util.ts
@permobil/nativescript/src/utils/device.util.d.ts
@permobil/nativescript/src/utils/device.util.ts
@permobil/nativescript/src/utils/i18n.util.ts
@permobil/nativescript/src/utils/index.ts
apps/wear/pushtracker/app/app.ts
apps/wear/pushtracker/app/assets/i18n/da.json
apps/wear/pushtracker/app/assets/i18n/de.json
apps/wear/pushtracker/app/assets/i18n/en.json
apps/wear/pushtracker/app/assets/i18n/es.json
apps/wear/pushtracker/app/assets/i18n/fr.json
apps/wear/pushtracker/app/assets/i18n/it.json
apps/wear/pushtracker/app/assets/i18n/ja.json
apps/wear/pushtracker/app/assets/i18n/ko.json
apps/wear/pushtracker/app/assets/i18n/nb.json
apps/wear/pushtracker/app/assets/i18n/nl.json
apps/wear/pushtracker/app/assets/i18n/sv.json
apps/wear/pushtracker/app/assets/i18n/zh.json
apps/wear/pushtracker/app/namespaces/profile.ts
apps/wear/pushtracker/app/pages/modals/change-settings/change-settings-view-model.ts
apps/wear/pushtracker/app/pages/modals/settings/settings.xml
apps/wear/smartdrive/app/app.ts
apps/wear/smartdrive/app/assets/i18n/en.json
apps/wear/smartdrive/app/models/watch-settings.ts
apps/wear/smartdrive/app/pages/modals/settings/settings-view-model.ts
package.json

Feat: PT.W language change

---

apps/wear/smartdrive/app/App_Resources/Android/src/main/java/com/permobil/smartdrive/wearos/watchface/digital/DigitalWatchFaceConfigActivity.java
apps/wear/smartdrive/app/App_Resources/Android/src/main/res/layout/activity_config.xml

To closer mirror the layout changes made to the watchface itself to support more device screens.

Feat: sd watchface config complication layout updates

---

apps/wear/pushtracker/app/main-activity.ts

Bug (PT.W) add @nativeclass to main-activity classes

---

apps/mobile/pushtracker/tools/android-release.js
apps/mobile/smart-eval/tools/android-release.js
apps/wear/pushtracker/tools/android-release.js
apps/wear/smartdrive/tools/android-release.js
package.json

removes the sourcemaps flag from various scripts

closes #742

---

apps/wear/smartdrive/app/utils/notifications.ts

feat: cancel handler for SC notifications

---

apps/wear/pushtracker/App_Resources/Android/src/main/java/com/permobil/pushtracker/wearos/ActivityService.java
apps/wear/pushtracker/app/utils/notifications.ts

* added image to coast record notification
* fixed incorrect icon for recurring notifications.
* removed unused code.

Fix notification style for PT.W

---

apps/mobile/pushtracker/src/app/modules/activity/activity.component.ts
apps/mobile/pushtracker/src/app/modules/home-tab/home-tab.component.ts
apps/mobile/pushtracker/src/app/modules/journey-tab/journey-tab.component.ts

makes it consistent w.r.t. stable for fewer diffs later down the line.

removed unused variables.

---

apps/wear/smartdrive/app/pages/main-page/main-view-model.ts

refactored the logic around disabling power assist and asking for permissions - ensure multiple redundant popups do not pop up when requesting for permissions that have been / are being denied; always disable power assist and do not return early from it to better ensure that it fully disables; only predicate the vibration on the power assist and motor state. allow forceStop caller to override _ensuringBluetooth guard on disable power assist.

Minor cleanup around permissions requests for power assist

---

apps/mobile/pushtracker/src/app/assets/i18n/en.json

fix translation file
